import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";
import ConditionalFooter from "../components/ConditionalFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ireland Votes Election Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-hidden bg-[#1f1f1f] text-white">

        {/* NAVBAR */}
        <Navbar />

{/* MAIN CONTENT */}
<div className="flex-1 flex overflow-hidden">
  {children}
</div>

{/* FOOTER */}
<ConditionalFooter />

      </body>
    </html>
  );
}