import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";
import ConditionalFooter from "../components/ConditionalFooter";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ireland Votes Election Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html
  lang="en"
  className={`${inter.variable} h-full antialiased`}
  suppressHydrationWarning
>
<body
className="h-screen flex flex-col overflow-hidden"
style={{
  background: "var(--bg)",
  color: "var(--text)"
}}
>

        {/* NAVBAR */}
        <Navbar />

{/* MAIN CONTENT */}
<div className="flex-1 flex overflow-hidden">
  {children}
</div>

{/* FOOTER */}
<ConditionalFooter />

      </body>
    </html>
  );
}