import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";
import ConditionalFooter from "../components/ConditionalFooter";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ireland Votes Election Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col overflow-hidden bg-[#1f1f1f] text-white">

        {/* NAVBAR */}
        <Navbar />

{/* MAIN CONTENT */}
<div className="flex-1 flex overflow-hidden text-white">
  {children}
</div>

{/* FOOTER */}
<ConditionalFooter />

      </body>
    </html>
  );
}